<template>

      <div class="card text-center">
        
        <div style=" margin: 2%;">
                {{info.task}}
            </div>
      </div>

</template>

<script>
import store from '@/store.js'

export default {
  props: [ "info"],
  data () {
    return {
      global: store,
    }
  },
  
  
}
</script>

<style>
  .card {
    margin-bottom: 10px
  }
  .comments {
    margin: 20px 0
  }

  /* ----------------------------------------------
  * Generated by Animista on 2020-1-3 19:19:35
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */
  @-webkit-keyframes fade-in-fwd{0%{-webkit-transform:translateZ(-80px);transform:translateZ(-80px);opacity:0}100%{-webkit-transform:translateZ(0);transform:translateZ(0);opacity:1}}@keyframes fade-in-fwd{0%{-webkit-transform:translateZ(-80px);transform:translateZ(-80px);opacity:0}100%{-webkit-transform:translateZ(0);transform:translateZ(0);opacity:1}}
  .animate{-webkit-animation:fade-in-fwd 1s cubic-bezier(.39,.575,.565,1.000) both;animation:fade-in-fwd 1s cubic-bezier(.39,.575,.565,1.000) both}

</style>